# Generated by Django 5.0.6 on 2024-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_uor_chef_facebook_alter_uor_chef_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title', models.CharField(max_length=255, verbose_name='описание')),
                ('banner', models.ImageField(upload_to='banner/', verbose_name='Фото баннера')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
    ]
