# Generated by Django 5.0.6 on 2024-07-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='sub_title',
            field=models.CharField(max_length=255, verbose_name='Новость'),
        ),
    ]
