# Generated by Django 5.0.6 on 2024-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_news_options_rename_sub_title_news_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='estitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Заловок'),
        ),
    ]
