# Generated by Django 5.0.6 on 2024-07-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_news_estitle_alter_news_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='estitle',
            field=models.CharField(default='', max_length=255, verbose_name='Новость'),
        ),
    ]
